---
title: "Simple document"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
```

## Import some data

I want to import "FAS_litters.csv". (tell R where the data is)

```{r}
litters_df = read_csv("data/FAS_litters.csv")
#This is relative path, below is absolute path, starting from very beginning
```

```{r}
read_csv("/Users/kexu/Desktop/data_wrangling/data/FAS_litters.csv")
#absolute path, only work in this computer
```

I imported this data set. Now I want better names.

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
#clean up names, no space in names like Growth Year => Growth_Year

#janitor is a pacakge, but I only need cleean_names in this pacakge, so I do not need to library it, just type the code above
```

I have netter names now. Let's look at data set.

```{r}
litters_df

head(litters_df, 20)
tail(litters_df, 20)
#see first / last 20 rows
```

```{r, eval=FALSE}
view(litters_df)
# view here means you can open your data in a new window
```

Here is 'skimr':
```{r}
skimr::skim(litters_df)
# like a summary table for your data
```

## Arguments in `read_csv`

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5, #skip first 5 rows
    colnames = FALSE, #skip first 5 rows and the 1st row is no longer column names in new data set
    na = "Low8") #delete the name of variables whose names is Low8
```


## Parsing columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv", #. means starting from here
  col_types = cols( # set and unique column type
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```




