---
title: "Tidy data"
author: "ke"
date: "10/3/2021"
output: github_document
---

```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot longer

(Don't use `gather()`, always use `pivot_longer`)
Load the PULSE data.

```{r}
pulse_df = 
  read_sas("data//public_pulse_data.sas7bdat")%>%
  janitor::clean_names()
```

Let's try to pivot

```{r}
# make data table computer readable

pulse_tidy = 
  pulse_df %>%
  pivot_longer(            # ?pivot_longer
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",  #data frame中省略variable名字中"bdi_score_"这一部分
    values_to = "bdi"
  ) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"), 
    #In this "visit" column, any elements that called "bl" are changed to "00m"
    visit = factor(visit) #convert "visit" into factor
  )
```

## pivot_wider

(Don't use `spread()`, always use `pivot_wider`)

make up a results data table

```{r}
# make data table human readable

analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a", "b", "a", "b"),
    group_mean = c(4, 8, 3, 6)
  )

analysis_df %>%
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  )
knitr::kable() # make r_markdown realize it is a table, output a table format
```


## bind rows

(Never use `rbind()`, always use `bind_rows()`)

import the LotR movie word stuff

```{r}
# read three tables in excel file

fellowship_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")%>%
  mutate(movie = "fellowship_rings")

two_towers_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6")%>%
  mutate(movie = "two_towers")

return_df = 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6")%>%
  mutate(movie = "return_king")

lotr_df = 
  bind_rows(fellowship_df, two_towers_df, return_df)%>%
  janitor::clean_names()%>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  )%>%
  
  # relocate columns, 把movie column move to the first column
  relocate(movie)
```


## Joins

Look at FAS data. This imports and cleans litters and pups data.

```{r}
litters_df =
  read_csv("data/FAS_litters.csv")%>%
  janitor::clean_names()%>%
  # seperate group variable into two columns
  separate(group, into = c("dose", "day_of_treatment"), 3)%>% # 3 means split column name in which letter: "con 7", if 2, then: "co n7"
  relocate(litter_number)%>%
  mutate(dose = str_to_lower(dose))


pups_df = 
  read_csv("data/FAS_pups.csv")%>%
  janitor::clean_names()%>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))%>% #recode: give it a variable, tell it what and how you wanna change
  mutate(sex = recode(sex, `male` = "1", `female` = "2")) #注意`` 和 ""
```


Let's join these up

```{r}
das_df = 
  left_join(pups_df, litters_df, by = "litter_number")%>% # join two table together
  relocate(litter_number, dose, day_of_treatment) # relocate columns following this order
```





